from typing import TypedDict, List, Dict, Any

from pydantic import BaseModel, Field
from langchain_openai import ChatOpenAI
from langchain_core.output_parsers import JsonOutputParser

from src.config import DEFAULT_TEMPERATURE, TOP_K_RETRIEVAL
from src.prompts import (
    EVIDENCE_FILTER_PROMPT,
    CLASSIFIER_PROMPT,
    VERIFIER_PROMPT,
)
from src.pinecone_utils import (
    initialize_pinecone,
    initialize_embedding_model,
    retrieve_from_pinecone,
    format_retrieved_docs,
)
from src.lora_utils import generate_lora_response, parse_lora_output


# ----------------------------
# Shared graph state
# ----------------------------
class AgentState(TypedDict):
    user_query: str
    retrieved_docs: List[Dict[str, Any]]
    filtered_docs: List[Dict[str, Any]]
    classification: str
    explanation: str
    verification: str
    needs_retry: bool
    retry_count: int
    final_answer: str
    classifier_mode: str  # "base" or "lora"


# ----------------------------
# Pydantic output schemas
# ----------------------------
class GradeBinary(BaseModel):
    binary_score: str = Field(description="'yes' or 'no'")


class ClassificationOutput(BaseModel):
    label: str = Field(description="'spam' or 'ham'")
    explanation: str = Field(description="Short explanation")


# ----------------------------
# LLM factory
# ----------------------------
def get_llm():
    """
    Default LLM setup.
    Expects OPENAI_API_KEY in environment.
    """
    return ChatOpenAI(model="gpt-4o-mini", temperature=DEFAULT_TEMPERATURE)


# ----------------------------
# Node 1: retrieve
# ----------------------------
def retrieve_from_pinecone_node(state: AgentState) -> AgentState:
    index = initialize_pinecone()
    model = initialize_embedding_model()

    retrieved_docs = retrieve_from_pinecone(
        query_text=state["user_query"],
        index=index,
        model=model,
        top_k=TOP_K_RETRIEVAL,
    )

    return {
        **state,
        "retrieved_docs": retrieved_docs,
    }


# ----------------------------
# Node 2: filter evidence
# ----------------------------
def filter_evidence_node(state: AgentState) -> AgentState:
    llm = get_llm()
    parser = JsonOutputParser()

    filtered_docs = []

    for doc in state["retrieved_docs"]:
        chain = EVIDENCE_FILTER_PROMPT | llm | parser
        result = chain.invoke(
            {
                "question": state["user_query"],
                "document": doc["text"],
            }
        )

        binary_score = result.get("binary_score", "").strip().lower()
        if binary_score == "yes":
            filtered_docs.append(doc)

    return {
        **state,
        "filtered_docs": filtered_docs,
    }


# ----------------------------
# Node 3A: classify with base model
# ----------------------------
def classify_sms_base_node(state: AgentState) -> AgentState:
    llm = get_llm()
    parser = JsonOutputParser()

    docs_text = format_retrieved_docs(state["filtered_docs"])

    chain = CLASSIFIER_PROMPT | llm | parser
    result = chain.invoke(
        {
            "question": state["user_query"],
            "documents": docs_text,
        }
    )

    classification = result.get("label", "").strip().lower()
    explanation = result.get("explanation", "").strip()

    return {
        **state,
        "classification": classification,
        "explanation": explanation,
    }


# ----------------------------
# Node 3B: classify with LoRA model
# ----------------------------
def classify_sms_lora_node(state: AgentState) -> AgentState:
    docs_text = format_retrieved_docs(state["filtered_docs"])
    output = generate_lora_response(state["user_query"])
    parsed = parse_lora_output(output)

    classification = parsed.get("label", "").strip().lower()

    explanation = (
        "The prediction was generated by the fine-tuned LoRA SMS classifier. "
        f"Retrieved evidence was available for support during the workflow. "
        f"Evidence count: {len(state['filtered_docs'])}."
    )

    return {
        **state,
        "classification": classification,
        "explanation": explanation,
    }


# ----------------------------
# Node 4: verify
# ----------------------------
def verify_classification_node(state: AgentState) -> AgentState:
    llm = get_llm()
    parser = JsonOutputParser()

    docs_text = format_retrieved_docs(state["filtered_docs"])

    chain = VERIFIER_PROMPT | llm | parser
    result = chain.invoke(
        {
            "question": state["user_query"],
            "documents": docs_text,
            "classification": state["classification"],
            "explanation": state["explanation"],
        }
    )

    binary_score = result.get("binary_score", "").strip().lower()
    supported = (binary_score == "yes")

    return {
        **state,
        "verification": "supported" if supported else "unsupported",
        "needs_retry": not supported,
        "retry_count": state["retry_count"] + (0 if supported else 1),
    }


# ----------------------------
# Node 5: finalize
# ----------------------------
def finalize_output_node(state: AgentState) -> AgentState:
    docs_used = len(state["filtered_docs"])

    final_answer = (
        f"Prediction: {state['classification'].upper()}\n"
        f"Explanation: {state['explanation']}\n"
        f"Evidence examples used: {docs_used}\n"
        f"Verification: {state['verification']}\n"
        f"Classifier mode: {state['classifier_mode']}"
    )

    return {
        **state,
        "final_answer": final_answer,
    }