"""Qualitative demo runner.

Runs five hand-picked SMS queries across all comparison modes and writes the
results to ``outputs/comparison_results.md``.

NOTE: this script is qualitative/demo-only. The quantitative benchmark
(introduced in Phase 2 of the v2 upgrade) will live in ``src/benchmark.py`` and
will be the source of truth for accuracy / precision / recall / F1.
"""

from pathlib import Path

from src.evaluation import run_all_modes


QUERIES = [
    "Congratulations! You have won a free prize. Call now to claim.",
    "Hey, are we still meeting for lunch at 12 today?",
    "URGENT! Your mobile number has won £5000. Reply now to claim.",
    "Can you send me the notes from class when you get a chance?",
    "You have been specially selected for a cash reward. Call this number immediately.",
]

OUTPUT_PATH = Path("outputs/comparison_results.md")


def format_block(title: str, content: str) -> str:
    return f"### {title}\n\n{content.strip()}\n"


def main() -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "# Comparison Results (Qualitative Demo)\n",
        "_This file is a qualitative demo across five hand-picked queries._  ",
        "_For quantitative metrics, see `outputs/benchmark_summary.md` "
        "(generated by `python -m src.benchmark`)._\n",
    ]

    for i, query in enumerate(QUERIES, start=1):
        results = run_all_modes(query)

        lines.append(f"## Query {i}\n")
        lines.append(f"**Input:**  \n{query}\n")

        lines.append(format_block("Base LLM (No RAG)", results["base_llm"]["raw_output"]))
        lines.append(format_block("Basic RAG", results["basic_rag"]["raw_output"]))
        lines.append(
            format_block(
                "Advanced Agentic RAG with Base Model",
                results["advanced_rag_base"]["final_answer"],
            )
        )
        lines.append(
            format_block(
                "Advanced Agentic RAG with Fine-Tuned LoRA Model",
                results["advanced_rag_lora"]["final_answer"],
            )
        )
        lines.append(
            format_block(
                "Guarded Fallback (LoRA -> Verify -> Base if unsupported)",
                results["guarded_fallback"]["final_answer"],
            )
        )
        lines.append("---\n")

    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Saved comparison results to: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
